package com.legacypilot.entity;

/**
 * Logical project that groups repositories and incident analysis tasks.
 */
public record LegacyProject(
        /** Stable project ID generated by the backend. */
        String projectId,
        /** User-facing project name. */
        String name,
        /** Optional default remote repository URL. */
        String repositoryUrl,
        /** Default branch used when repo requests omit branch. */
        String defaultBranch,
        /** ISO-8601 creation timestamp. */
        String createdAt
) {
}
