package com.legacypilot.repository.entity;

/**
 * Repository connection/index metadata.
 *
 * The name is still RepositoryIndex because the record is the future bridge to
 * GitNexus graph indexing. For now it records where the source code lives and
 * which commit is being analyzed.
 */
public record RepositoryIndex(
        /** Stable repository connection ID generated by the backend. */
        String repoId,
        /** Project that owns this repository. */
        String projectId,
        /** How this repository was connected: local path or future Git URL. */
        RepositorySourceType sourceType,
        /** Remote origin URL when known. */
        String repositoryUrl,
        /** Local path that GitNexus/RAG should read. */
        String localRepoPath,
        /** Branch observed or requested for analysis. */
        String branch,
        /** Commit SHA observed or requested for analysis. */
        String commitSha,
        /** Future GitNexus graph identifier. */
        String graphId,
        /** Task created for connecting/indexing this repository. */
        String taskId,
        /** ISO-8601 creation timestamp. */
        String createdAt
) {
}
